booking:
  image: koenighotze/jee7hotelbooking
  ports:
    - 8080:8080
    - 9990:9990
  links:
    - mongodb
    - guest
  environment:
    - MONGO_URI=mongodb
    - GUEST_URI=guest:8080
guest:
  image: koenighotze/jee7hotelguest
  ports:
    - 8081:8080
  expose:
    - 8080
mongodb:
  container_name: jee7hotelmongo
  image: mongo:3.1.9
  expose:
    - "27017"


#guest:
#  image: koenighotze/jee7hotelguest
#  ports:
#    - 8081:8080
#  expose:
#    - 8080
#mongodb:
#  image: mongo:3.1.9
#  expose:
#    - "27017"
#booking:
#  image: koenighotze/jee7hotelbooking
#  ports:
#    - 8080:8080
#    - 9990:9990
#  environment:
#    - MONGO_URI=mongodb
#    - GUEST_URI=guest:8081
#  links:
#   - mongodb
#   - guest
